[pytest]
testpaths = testCases
python_files = uw_flow_*.py test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short --html-report=Reports/latest_report.html --title="Underwriter API Automation Regression Report"
console_output_style = count
filterwarnings =
    ignore::urllib3.exceptions.InsecureRequestWarning
