[pytest]
testpaths = tests
python_files = uw_flow_*.py test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short --html=reports/latest_report.html --self-contained-html
console_output_style = count
filterwarnings =
    ignore::urllib3.exceptions.InsecureRequestWarning
